-- =============================================
--    DISTRIBUTOR PERFORMANCE AND CREDIT RISK
-- =============================================

-- What percentage of revenue is generated by the top 10 distributor?

WITH distributor_revenue AS (
SELECT
distributor_id,
SUM(revenue) AS revenue
FROM sales_base
GROUP BY distributor_id
),

ranked AS (
SELECT
distributor_id,
revenue,
ROW_NUMBER() OVER (ORDER BY revenue DESC) AS rnk
FROM distributor_revenue
),

total_revenue AS (
SELECT SUM(revenue) AS total_rev
FROM distributor_revenue
)

SELECT
ROUND(
(SUM(r.revenue) * 100.0 / MAX(t.total_rev))::numeric, 2) AS top10_revenue_share
FROM ranked r
CROSS JOIN total_revenue t
WHERE r.rnk <= 10;

-- Which distributors have the highest payment delays?

SELECT
o.order_id,
o.distributor_id,

(o.payment_received_date::date - o.dispatch_date::date) 
AS actual_payment_days,

d.avg_payment_days 
AS expected_payment_days,

(o.payment_received_date::date - o.dispatch_date::date) 
- d.avg_payment_days 
AS delay_days,

CASE
WHEN (o.payment_received_date::date - o.dispatch_date::date) - d.avg_payment_days < -15
THEN 'Early Payment'

WHEN (o.payment_received_date::date - o.dispatch_date::date) - d.avg_payment_days BETWEEN -15 AND 15
THEN 'On-Time Payment'

WHEN (o.payment_received_date::date - o.dispatch_date::date) - d.avg_payment_days BETWEEN 16 AND 90
THEN 'Late Payment'

ELSE 'Extreme Late Payment'
END AS payment_profile

FROM orders o
JOIN distributors d
ON o.distributor_id = d.distributor_id

WHERE o.status = 'completed';

-- How many orders were there in each payment received category?

WITH payment_profile_table AS (

SELECT
o.order_id,
o.distributor_id,

(o.payment_received_date::date - o.dispatch_date::date)
AS actual_payment_days,

d.avg_payment_days
AS expected_payment_days,

(o.payment_received_date::date - o.dispatch_date::date)
- d.avg_payment_days
AS delay_days,

CASE
WHEN (o.payment_received_date::date - o.dispatch_date::date) - d.avg_payment_days < -15
THEN 'Early Payment'

WHEN (o.payment_received_date::date - o.dispatch_date::date) - d.avg_payment_days BETWEEN -15 AND 15
THEN 'On-Time Payment'

WHEN (o.payment_received_date::date - o.dispatch_date::date) - d.avg_payment_days BETWEEN 16 AND 90
THEN 'Late Payment'

ELSE 'Extreme Late Payment'
END AS payment_profile

FROM orders o
JOIN distributors d
ON o.distributor_id = d.distributor_id

WHERE o.status = 'completed'

)

SELECT
payment_profile,
COUNT(*) AS orders
FROM payment_profile_table
GROUP BY payment_profile
ORDER BY orders DESC;

-- How frequently does each distributor place orders?

SELECT 
distributor_id,
COUNT(order_id) AS total_orders,
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
(MAX(order_date)::date - MIN(order_date)::date) AS active_days,
ROUND((MAX(order_date)::date - MIN(order_date)::date)::numeric/NULLIF(COUNT(order_id)-1,0),2) AS avg_days_between_orders
FROM orders 
WHERE status = 'completed'
GROUP BY distributor_id
ORDER BY total_orders DESC; 

